name: "Checkout recursively with submodules and LFS"
description: "Installs tt-metal extra dev dependencies on ubuntu-20.04 GitHub Actions runners"

inputs:
  token:
    description: "Token with which to do the checkout"
    required: true
  fetch-depth:
    description: "Fetch depth for checkout"
    required: true
    default: 1

runs:
  using: "composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        token: ${{ inputs.token }}
        fetch-depth: ${{ inputs.fetch-depth }}
        lfs: true
        submodules: recursive
    - name: Fetch and pull LFS objects for each submodule
      shell: bash
      run: git submodule foreach 'git lfs fetch --all && git lfs pull'
