name: Changelog creation test flow

on:
  push:
    branches: ["main", "release"]
  workflow_dispatch:

jobs:
  get-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Create changelog
        id: create-changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ignorePreReleases: true
          failOnError: true
      - name: Output changelog
        run: echo "${{ steps.create-changelog.outputs.changelog }}"
