name: "[BUILD FAILED] Labelling_Corrections"
on:
  workflow_run:
    workflows: ["dummy_workflow"]
    types:
      - completed

jobs:
  detect_completion:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Octokit
        run: npm install @octokit/core
        
      - name: Status Check
        id: check_status
        uses: actions/github-script@v2.1.0
        with:
          script: |
            const workflowStatus = ${{ toJSON(github.event.workflow_run) }};
            const status = workflowStatus.conclusion;
            const workflowId = workflowStatus.id;
            console.log(`The status of the completed workflow is: ${status}`);

            // Fetch the logs for the previous workflow run
            const response = await octokit.actions.listWorkflowRunJobs({
              owner: github.context.payload.repository.owner.login,
              repo: github.context.payload.repository.name,
              run_id: workflowId,
            });

            // Check for failed steps
            const failedSteps = response.data.jobs.filter(job => job.conclusion === 'failure').map(job => job.name);

            if (status === 'success') {
              // Add your actions for a successful workflow completion here
              console.log('The workflow was successful! ');
            } else if (status === 'failure') {
              // Add your actions for a failed workflow completion here
              console.log('The workflow failed!');
              console.log('The failed steps are:', failedSteps);
            } else {
              console.log('The workflow encountered an unknown outcome.');
            }
